### ISSUE TITLE
Update web-angular template

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/stagehand#590]
I believe we should have these dependencies (updating angular, angular_components, angular_test, and build_web_compilers):

```
environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_components: ^0.11.0

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
  test: ^1.5.1
```
