### ISSUE TITLE
[Feature] Support create null-safety package

### ISSUE THREAD

**Issue by Sunbreak** [dart-lang/stagehand#694]
# Background

Dart-2.12.0 is release on stable channel and null-safety is populating around the community

But now we could only create non-null-safety Dart package with stagehand

- when activate stagehand, there are several upgradable dependencies

```sh
C:\Users\Admin>pub global activate stagehand
Resolving dependencies...
+ args 1.6.0 (2.0.0 available)
+ charcode 1.2.0
+ collection 1.15.0
+ http 0.12.2 (0.13.0 available)
+ http_parser 3.1.4 (4.0.0 available)
+ path 1.8.0
+ pedantic 1.11.0
+ source_span 1.8.1
+ stagehand 3.3.11
+ string_scanner 1.1.0
+ term_glyph 1.2.0
+ typed_data 1.3.0
+ usage 3.4.2 (4.0.0 available)
Downloading stagehand 3.3.11...
Precompiling executables...
Precompiled stagehand:stagehand.
Installed executable stagehand.
Activated stagehand 3.3.11.
```

- when create simple console app, it is depends on non-null-safety package

```sh
C:\Users\Admin>mkdir dart_package

C:\Users\Admin>cd dart_package

C:\Users\Admin\dart_package>stagehand console-simple
Creating console-simple application `dart_package`:
  C:\Users\Admin\dart_package\.gitignore
  C:\Users\Admin\dart_package\CHANGELOG.md
  C:\Users\Admin\dart_package\README.md
  C:\Users\Admin\dart_package\analysis_options.yaml
  C:\Users\Admin\dart_package\bin/dart_package.dart
  C:\Users\Admin\dart_package\pubspec.yaml
6 files written.

--> to provision required packages, run 'pub get'
--> run your app using `dart bin/__projectName__.dart`.

C:\Users\Admin\dart_package>type pubspec.yaml
```

```yaml
name: dart_package
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
```

# Expect

stagehand 3.3.11-nullsafety.0 or 4.0 supports **Null-Safety**
